dommel_lats_homepage:
    path:     /
    defaults: { _controller: DommelLatsBundle:Default:index }
    methods:  [GET]

dommel_lats_sensor_listing:
    path:     /v1/sensors
    defaults: { _controller: DommelLatsBundle:Sensor:getSensors }
    methods:  [GET]

dommel_lats_sensor_data:
    path:     /v1/sensors/{name}
    defaults: { _controller: DommelLatsBundle:Sensor:getSensor }
    methods:  [GET]

dommel_lats_livesensor_data:
    path:     /v1/livesensors/{name}
    defaults: { _controller: DommelLatsBundle:LiveSensor:getSensor }
    methods:  [GET]
